from os import environ

FLASK_ENV = environ.get("FLASK_ENV")
SQLALCHEMY_DATABASE_URI = environ.get("SQLALCHEMY_DATABASE_URI")
FLASK_DEBUG = environ.get("FLASK_DEBUG")
SQLALCHEMY_TRACK_MODIFICATIONS = environ.get("SQLALCHEMY_TRACK_MODIFICATIONS")
SECRET_KEY = environ.get("SECRET_KEY")
